version: "3.9"

services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile.manager
    environment:
      - EXPECTED_NODE_COUNT=3
    ports:
      - "9005:9005"
    volumes:
      - ./config:/config
    networks:
      - craq-net

  node1:
    build:
      context: .
      dockerfile: Dockerfile.node
    depends_on:
      - manager
    environment:
      - NODE_ID=n1
      - NODE_ADDRESS=localhost:8001
    ports:
      - "8001:8001"
    volumes:
      - ./config:/config
    networks:
      - craq-net

  node2:
    build:
      context: .
      dockerfile: Dockerfile.node
    depends_on:
      - manager
    environment:
      - NODE_ID=n2
      - NODE_ADDRESS=localhost:8002
    ports:
      - "8002:8002"
    volumes:
      - ./config:/config
    networks:
      - craq-net

  node3:
    build:
      context: .
      dockerfile: Dockerfile.node
    depends_on:
      - manager
    environment:
      - NODE_ID=n3
      - NODE_ADDRESS=localhost:8003
    ports:
      - "8003:8003"
    volumes:
      - ./config:/config
    networks:
      - craq-net

networks:
  craq-net:
    driver: bridge
