# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build - Node
      run: go build -o craq-node ./cmd/node/main.go

    - name: Build - Manager
      run: go build -o craq-manager ./cmd/manager/main.go

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          craq-node
          craq-manager
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
